In [6]:

%matplotlib inline

In [11]:
from pprint import pprint as pp
import matplotlib as mpl
import numpy as np
import os
import pandas as pd
# import sklearn
import sys
import tensorflow as tf
from tensorflow import keras
import time

In [12]:
for module in mpl, np, pd, tf, keras:
    pp({
        "module": module.__name__,
        "version": module.__version__
    })

{'module': 'matplotlib', 'version': '3.5.1'}
{'module': 'numpy', 'version': '1.19.5'}
{'module': 'pandas', 'version': '1.4.0'}
{'module': 'tensorflow', 'version': '2.7.0'}
{'module': 'keras.api._v2.keras', 'version': '2.7.0'}


In [13]:
assert sys.version_info >= (3, 5) # Python ≥3.5 required
assert tf.__version__ >= "2.0"    # TensorFlow ≥2.0 required

## Tensors and operations

### tf.constant 

In [15]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const')>

In [16]:
dir(tf.constant)

['__annotations__',
 '__call__',
 '__class__',
 '__closure__',
 '__code__',
 '__defaults__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__get__',
 '__getattribute__',
 '__globals__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__kwdefaults__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_tf_api_names',
 '_tf_api_names_v1']

In [17]:
help(tf.constant)

Help on function constant in module tensorflow.python.framework.constant_op:

constant(value, dtype=None, shape=None, name='Const')
    Creates a constant tensor from a tensor-like object.
    
    Note: All eager `tf.Tensor` values are immutable (in contrast to
    `tf.Variable`). There is nothing especially _constant_ about the value
    returned from `tf.constant`. This function is not fundamentally different from
    `tf.convert_to_tensor`. The name `tf.constant` comes from the `value` being
    embedded in a `Const` node in the `tf.Graph`. `tf.constant` is useful
    for asserting that the value can be embedded that way.
    
    If the argument `dtype` is not specified, then the type is inferred from
    the type of `value`.
    
    >>> # Constant 1-D Tensor from a python list.
    >>> tf.constant([1, 2, 3, 4, 5, 6])
    <tf.Tensor: shape=(6,), dtype=int32,
        numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
    >>> # Or a numpy array
    >>> a = np.array([[1, 2, 3], [4, 5, 6]

#### Constant OPS

`tensorflow.python.framework.constant_op`

In [18]:
from tensorflow.python.framework import constant_op

In [19]:
constant_op

<module 'tensorflow.python.framework.constant_op' from '/Users/allan.chepkoy/.local/share/virtualenvs/zora-rZyFQzhX/lib/python3.8/site-packages/tensorflow-2.7.0-py3.8-macosx-11-x86_64.egg/tensorflow/python/framework/constant_op.py'>

In [21]:
dir(constant_op)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_constant_eager_impl',
 '_constant_impl',
 '_constant_tensor_conversion_function',
 '_dimension_tensor_conversion_function',
 '_eager_const',
 '_eager_fill',
 '_eager_identity',
 '_eager_reshape',
 '_tensor_shape_tensor_conversion_function',
 'absolute_import',
 'attr_value_pb2',
 'constant',
 'constant_v1',
 'context',
 'convert_to_eager_tensor',
 'division',
 'dtypes',
 'execute',
 'is_constant',
 'op_callbacks',
 'ops',
 'print_function',
 'tensor_shape',
 'tensor_util',
 'tf_export',
 'trace',
 'types_pb2']

In [24]:
value = 3

tf.constant(value, dtype=None, shape=None, name='Const')

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [139]:
def gen_const(values, eager_mode = False):  
    if eager_mode == False:
        name = None
        
    else: 
        name = name
        
    value, name = values
    print(name)
    constant = tf.constant(value, dtype=None, shape=None)
    pp( {
        "dtype": constant.dtype,
        "shape": constant.shape,
#         "name": constant.name
        "backing_device": constant.backing_device,
        "consumers": constant.consumers,
        "cpu": constant.cpu,
        "device": constant.device,
        "eval": constant.eval,
        "experimental_ref": constant.experimental_ref(),
        "get_shape": constant.get_shape,
        "gpu": constant.gpu,
#         "dir" : dir(constant),
#         'graph':constant.graph,
         'is_packed':constant.is_packed,
#          'name'constant.,
         'ndim':constant.ndim,
         'numpy':constant.numpy,
#          'op':constant.op,
         'ref':constant.ref,
         'set_shape':constant.set_shape,
         'shape':constant.shape,
#          'value_index':constant.value_index
    }
    )

In [140]:
gen_const((0, "scalar"), False)

scalar
{'backing_device': '/job:localhost/replica:0/task:0/device:CPU:0',
 'consumers': <bound method _EagerTensorBase.consumers of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'cpu': <bound method _EagerTensorBase.cpu of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'device': '/job:localhost/replica:0/task:0/device:CPU:0',
 'dtype': tf.int32,
 'eval': <bound method _EagerTensorBase.eval of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'experimental_ref': <Reference wrapping <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'get_shape': <bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'gpu': <bound method _EagerTensorBase.gpu of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'is_packed': False,
 'ndim': 0,
 'numpy': <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'ref': <bound method Tensor.ref of <tf.Tensor: shape=(), dtype=int32, numpy=0>>,
 'set_shape': <bound method _EagerTensorBase.set_shape of <tf.T

In [58]:
gen_const(([3, 4, 8, 9, 9], "vector"))

vector
{'dtype': tf.int32, 'shape': TensorShape([5])}


In [60]:
gen_const(([[1, 2, 3], [1, 2, 3]], "Matrix"))

Matrix
{'dtype': tf.int32, 'shape': TensorShape([2, 3])}


In [63]:
matrix = {
    "row_one": [1, 2, 3],
    "row_two": [4, 5, 6]
}

In [71]:
row_one = list()

for i in range(10):
    row_one.append(i)

In [72]:
row_one

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
matrix_one = [[1, 2, 3],[4, 5, 6]]
matrix_two = [[1, 2, 3], [4, 5, 6]]


In [79]:
three_d = [matrix_one, matrix_two]

In [80]:
three_d

[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]

In [141]:
gen_const((three_d, "3D"))

3D
{'backing_device': '/job:localhost/replica:0/task:0/device:CPU:0',
 'consumers': <bound method _EagerTensorBase.consumers of <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>,
 'cpu': <bound method _EagerTensorBase.cpu of <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>,
 'device': '/job:localhost/replica:0/task:0/device:CPU:0',
 'dtype': tf.int32,
 'eval': <bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>,
 'experimental_ref': <Reference wrapping <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>>,
 'get_shape': <bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2

In [ ]:
## 

In [142]:
x1 = tf.constant([1, 2, 3])
x2 = tf.stack([x1, x1])

In [143]:
x2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [147]:
x3 = tf.stack([x2, x2])
x3

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [149]:
x4 = tf.stack([x3, x3])
x4

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]], dtype=int32)>

### Slicing

In [160]:
x = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

In [165]:
y = x[:, 1]

In [166]:
x[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [167]:
x[:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [169]:
x[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [170]:
x[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [171]:
x[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [172]:
x[:, 1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 5], dtype=int32)>

In [173]:
x[:, 2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

### Reshaping

In [174]:
reshaping = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

In [177]:
reshapingx = tf.reshape(reshaping, [3, 2])
reshapingx

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [181]:
reshapingy = tf.reshape(reshaping, [3, 2])
reshapingy

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Variable

In [182]:
v = tf.Variable(2.0, dtype=tf.float32, name = "my_var")
v

<tf.Variable 'my_var:0' shape=() dtype=float32, numpy=2.0>

In [183]:
v.assign(45.8)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=45.8>

In [184]:
v.assign_add(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=49.8>

In [185]:
v.assign_sub(3)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=46.8>

In [186]:
dir(v)

['SaveSliceInfo',
 '_OverloadAllOperators',
 '_OverloadOperator',
 '_TensorConversionFunction',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__complex__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ipow__',
 '__irealdiv__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__'

In [187]:
v2 = tf.Variable([[1., 2., 3.], [4., 5., 6.]])

In [188]:
v2

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [189]:
v2.value()

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [190]:
v2.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [192]:
v2.assign(v2 * v2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [193]:
v2[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 42.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [194]:
v2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 1., 42.,  9.], dtype=float32)>

In [195]:
v2[1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([16., 25., 36.], dtype=float32)>

In [196]:
v2[1].assign([7., 8., 9.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 42.,  9.],
       [ 7.,  8.,  9.]], dtype=float32)>

In [197]:
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


####  Ops

In [199]:
dir(tf)

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_API_MODULE',
 '_LazyLoader',
 '__all__',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__internal__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__operators__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_absolute_import',
 '_api',
 '_compat',
 '_current_file_location',
 '_current_module',
 '_distutils',
 '_division',
 '_estimator_module',
 '_fi',
 '_inspect',
 '_keras_module',
 '_keras_package',
 '_kernel_dir',
 '_ll'

In [200]:
help(tf.transpose)

Help on function transpose_v2 in module tensorflow.python.ops.array_ops:

transpose_v2(a, perm=None, conjugate=False, name='transpose')
    Transposes `a`, where `a` is a Tensor.
    
    Permutes the dimensions according to the value of `perm`.
    
    The returned tensor's dimension `i` will correspond to the input dimension
    `perm[i]`. If `perm` is not given, it is set to (n-1...0), where n is the rank
    of the input tensor. Hence by default, this operation performs a regular
    matrix transpose on 2-D input Tensors.
    
    If conjugate is `True` and `a.dtype` is either `complex64` or `complex128`
    then the values of `a` are conjugated and transposed.
    
    @compatibility(numpy)
    In `numpy` transposes are memory-efficient constant time operations as they
    simply return a new view of the same data with adjusted `strides`.
    
    TensorFlow does not support strides, so `transpose` returns a new tensor with
    the items permuted.
    @end_compatibility
    
    

#### To and From Numpy

In [208]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [210]:
b = tf.constant(a)
b

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]])>

In [211]:
b.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]])

#### Conflicting type

In [212]:
try:
    tf.constant(1) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]


In [213]:
try:
    tf.constant(1.0, dtype=tf.float64) + tf.constant(1.0)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a double tensor but is a float tensor [Op:AddV2]


In [214]:
t = tf.constant(1.0, dtype=tf.float64)
tf.cast(t, tf.float32) + tf.constant(1.0)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

#### Strings

In [215]:
t = tf.constant("café")
t

<tf.Tensor: shape=(), dtype=string, numpy=b'caf\xc3\xa9'>

In [216]:
tf.strings.length(t)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [217]:
tf.strings.length(t, unit="UTF8_CHAR")

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [218]:
tf.strings.unicode_decode(t, "UTF8")

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 233], dtype=int32)>

In [219]:
t = tf.constant(["Café", "Coffee", "caffè", "咖啡"])

In [220]:
t

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'Caf\xc3\xa9', b'Coffee', b'caff\xc3\xa8',
       b'\xe5\x92\x96\xe5\x95\xa1'], dtype=object)>

In [221]:
tf.strings.length(t, unit="UTF8_CHAR")
t

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'Caf\xc3\xa9', b'Coffee', b'caff\xc3\xa8',
       b'\xe5\x92\x96\xe5\x95\xa1'], dtype=object)>

In [222]:
r = tf.strings.unicode_decode(t, "UTF8")
r

<tf.RaggedTensor [[67, 97, 102, 233], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 232], [21654, 21857]]>

#### Ragged tensors

In [223]:
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41]])
r

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>

In [224]:
print(r)

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>


In [225]:
r[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([21, 22, 23], dtype=int32)>

In [226]:
r[1:2]

<tf.RaggedTensor [[21, 22, 23]]>

In [227]:
r2 = tf.ragged.constant([[51, 52], [], [71]])

In [228]:
r2

<tf.RaggedTensor [[51, 52], [], [71]]>

In [231]:
tf.concat([r, r2], axis=0)

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [71]]>

In [232]:
r3 = tf.ragged.constant([[13, 14, 15], [24], [], [42, 43]])
print(tf.concat([r, r3], axis=1))

<tf.RaggedTensor [[11, 12, 13, 14, 15], [21, 22, 23, 24], [], [41, 42, 43]]>


#### Sparse Tesors

In [233]:
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(s)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [234]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [235]:
s2 = s * 2.0

In [236]:
try:
    s3 = s + 1.
except TypeError as ex:
    print(ex)

unsupported operand type(s) for +: 'SparseTensor' and 'float'


In [237]:
s4 = tf.constant([[10., 20.], [30., 40.], [50., 60.], [70., 80.]])
tf.sparse.sparse_dense_matmul(s, s4)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 30.,  40.],
       [ 20.,  40.],
       [210., 240.]], dtype=float32)>

In [238]:
s5 = tf.SparseTensor(indices=[[0, 2], [0, 1]],
                     values=[1., 2.],
                     dense_shape=[3, 4])
print(s5)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([1. 2.], shape=(2,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [239]:
try:
    tf.sparse.to_dense(s5)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

indices[1] = [0,1] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.

 [Op:SparseToDense]


2022-01-31 14:22:27.643821: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at sparse_to_dense_op.cc:162 : INVALID_ARGUMENT: indices[1] = [0,1] is out of order. Many sparse ops require sorted indices.
    Use `tf.sparse.reorder` to create a correctly ordered copy.




In [240]:
s6 = tf.sparse.reorder(s5)
tf.sparse.to_dense(s6)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 2., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### Device

In [241]:
with tf.device("/cpu:0"):
    t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [242]:
t.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [243]:
if tf.config.list_physical_devices('GPU'):
    with tf.device("/gpu:0"):
        t2 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
    print(t2.device)